// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/zde37/Numeris-Task/internal/repository (interfaces: InvoiceRepository)
//
// Generated by this command:
//
//	mockgen -package mocked -destination internal/mock/invoice_repo.go github.com/zde37/Numeris-Task/internal/repository InvoiceRepository
//

// Package mocked is a generated GoMock package.
package mocked

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	models "github.com/zde37/Numeris-Task/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockInvoiceRepository is a mock of InvoiceRepository interface.
type MockInvoiceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInvoiceRepositoryMockRecorder
}

// MockInvoiceRepositoryMockRecorder is the mock recorder for MockInvoiceRepository.
type MockInvoiceRepositoryMockRecorder struct {
	mock *MockInvoiceRepository
}

// NewMockInvoiceRepository creates a new mock instance.
func NewMockInvoiceRepository(ctrl *gomock.Controller) *MockInvoiceRepository {
	mock := &MockInvoiceRepository{ctrl: ctrl}
	mock.recorder = &MockInvoiceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvoiceRepository) EXPECT() *MockInvoiceRepositoryMockRecorder {
	return m.recorder
}

// AddInvoiceActivity mocks base method.
func (m *MockInvoiceRepository) AddInvoiceActivity(arg0 context.Context, arg1 models.InvoiceActivity) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddInvoiceActivity", arg0, arg1)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddInvoiceActivity indicates an expected call of AddInvoiceActivity.
func (mr *MockInvoiceRepositoryMockRecorder) AddInvoiceActivity(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddInvoiceActivity", reflect.TypeOf((*MockInvoiceRepository)(nil).AddInvoiceActivity), arg0, arg1)
}

// CreateInvoice mocks base method.
func (m *MockInvoiceRepository) CreateInvoice(arg0 context.Context, arg1 models.Invoice, arg2 []models.InvoiceItem, arg3 uuid.UUID, arg4 models.PaymentInformation) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvoice", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInvoice indicates an expected call of CreateInvoice.
func (mr *MockInvoiceRepositoryMockRecorder) CreateInvoice(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvoice", reflect.TypeOf((*MockInvoiceRepository)(nil).CreateInvoice), arg0, arg1, arg2, arg3, arg4)
}

// GetInvoiceActivities mocks base method.
func (m *MockInvoiceRepository) GetInvoiceActivities(arg0 context.Context, arg1, arg2 uuid.UUID, arg3, arg4 int32) ([]models.InvoiceActivity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvoiceActivities", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]models.InvoiceActivity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvoiceActivities indicates an expected call of GetInvoiceActivities.
func (mr *MockInvoiceRepositoryMockRecorder) GetInvoiceActivities(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvoiceActivities", reflect.TypeOf((*MockInvoiceRepository)(nil).GetInvoiceActivities), arg0, arg1, arg2, arg3, arg4)
}

// GetInvoiceDetails mocks base method.
func (m *MockInvoiceRepository) GetInvoiceDetails(arg0 context.Context, arg1 uuid.UUID) (*models.InvoiceDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvoiceDetails", arg0, arg1)
	ret0, _ := ret[0].(*models.InvoiceDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvoiceDetails indicates an expected call of GetInvoiceDetails.
func (mr *MockInvoiceRepositoryMockRecorder) GetInvoiceDetails(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvoiceDetails", reflect.TypeOf((*MockInvoiceRepository)(nil).GetInvoiceDetails), arg0, arg1)
}

// GetRecentActivities mocks base method.
func (m *MockInvoiceRepository) GetRecentActivities(arg0 context.Context, arg1 uuid.UUID, arg2, arg3 int32) ([]models.RecentActivity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecentActivities", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]models.RecentActivity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecentActivities indicates an expected call of GetRecentActivities.
func (mr *MockInvoiceRepositoryMockRecorder) GetRecentActivities(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecentActivities", reflect.TypeOf((*MockInvoiceRepository)(nil).GetRecentActivities), arg0, arg1, arg2, arg3)
}

// GetRecentInvoices mocks base method.
func (m *MockInvoiceRepository) GetRecentInvoices(arg0 context.Context, arg1 uuid.UUID, arg2, arg3 int32) ([]models.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecentInvoices", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]models.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecentInvoices indicates an expected call of GetRecentInvoices.
func (mr *MockInvoiceRepositoryMockRecorder) GetRecentInvoices(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecentInvoices", reflect.TypeOf((*MockInvoiceRepository)(nil).GetRecentInvoices), arg0, arg1, arg2, arg3)
}

// GetTotalByStatus mocks base method.
func (m *MockInvoiceRepository) GetTotalByStatus(arg0 context.Context, arg1 models.InvoiceStatus) (float64, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalByStatus", arg0, arg1)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetTotalByStatus indicates an expected call of GetTotalByStatus.
func (mr *MockInvoiceRepositoryMockRecorder) GetTotalByStatus(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalByStatus", reflect.TypeOf((*MockInvoiceRepository)(nil).GetTotalByStatus), arg0, arg1)
}
