// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/zde37/Numeris-Task/internal/service (interfaces: UserService)
//
// Generated by this command:
//
//	mockgen -package mocked -destination internal/mock/user_service.go github.com/zde37/Numeris-Task/internal/service UserService
//

// Package mocked is a generated GoMock package.
package mocked

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	models "github.com/zde37/Numeris-Task/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// AddCustomer mocks base method.
func (m *MockUserService) AddCustomer(arg0 context.Context, arg1 models.AddCustomerRequest) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCustomer", arg0, arg1)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddCustomer indicates an expected call of AddCustomer.
func (mr *MockUserServiceMockRecorder) AddCustomer(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCustomer", reflect.TypeOf((*MockUserService)(nil).AddCustomer), arg0, arg1)
}

// AddPaymentMethod mocks base method.
func (m *MockUserService) AddPaymentMethod(arg0 context.Context, arg1 models.AddPaymentMethodRequest) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPaymentMethod", arg0, arg1)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPaymentMethod indicates an expected call of AddPaymentMethod.
func (mr *MockUserServiceMockRecorder) AddPaymentMethod(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPaymentMethod", reflect.TypeOf((*MockUserService)(nil).AddPaymentMethod), arg0, arg1)
}

// CreateUser mocks base method.
func (m *MockUserService) CreateUser(arg0 context.Context, arg1 models.CreateUserRequest) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserServiceMockRecorder) CreateUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserService)(nil).CreateUser), arg0, arg1)
}
